

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000


---

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis


---
spring.redis.host="localhost"
spring.redis.port="6379"
spring.security.oauth2.resourceserver.jwt.jwk-set-uri="http://localhost:9000"

---

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    
  show-actuator: true
  group-configs:
  - group: stores
    paths-to-match: /**
  - group: users
    packages-to-scan: com.hyundaimotors.hmb
