

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000


---

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis


---
spring.redis.host="localhost"
spring.redis.port="6379"
spring.security.oauth2.resourceserver.jwt.jwk-set-uri="http://localhost:9000"

---

