

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCESERVER_URL}
---
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${RESOURCESERVER_URL}
---

spring:
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
  cache:
    type: redis


---

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    
  show-actuator: true
  group-configs:
  - group: Lead
    packages-to-scan: 
      - com.hyundaimotors.hmb.cdppapp.controller.lead
      - com.hyundaimotors.hmb.cdppapp.controller.accesstocken
    
  - group: VOC
    packages-to-scan: 
      - com.hyundaimotors.hmb.cdppapp.controller.voc
      - com.hyundaimotors.hmb.cdppapp.controller.accesstocken
    
  - group: Foundation
    packages-to-scan: 
      - com.hyundaimotors.hmb.cdppapp.controller.foundation
      - com.hyundaimotors.hmb.cdppapp.controller.accesstocken
    
