package com.hyundaimotors.hmb.cdppapp.dto.IFHMBRECLAMEAQUICDPP0096;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class RetrieveTicketIdDto {
    private int rowId;
    private int id;
    private String underId;
    private String sourceExternalId;
    private String backDoingBusiness;
    private int commentsCount;
    private String company;
    private String companyConsideration;
    private String companyConsiderationDate;
    private String complaintContent;
    private String complaintTitle;
    private String consumerConsideration;
    private String consumerConsiderationDate;
    private String creationDate;
    private String customer;
    private String frozen;
    private String lastReplicaDate;
    private String moderation;
    private String personalizedFields;
    private String publicTreatmentTime;
    private String reclameAqui;
    private String raFeeling;
    private String raReason;
    private String raStatus;
    private String rafone;
    private String ratingWithoutResponse;
    private String requestEvaluation;
    private String requestModeration;
    private String resolvedIssue;
    private int ticketModerationsCount;
    private int assignmentCount;
    private String canLike;
    private int companyInteractionsCount;
    private int customerInteractionsCount;
    private String favorableAssessment;
    private String feedType;
    private String filed;
    private String historical;
    private String hugmeStatus;
    private String hugmeTicketType;
    private String informationSource;
    private int interactionsCount;
    private int interactionsNotReadedCount;
    private String lastModificationDate;
    private String privateTreatmentTime;
    private int redistributionsCount;
    private String redistributionsReason;
    private String source;
    private String tags;
    private String ticketDetailTypeId;
    private String ticketInteractionType;
    private int ticketMessagesCount;

    private String lastFeeling;
    private String moderationStatus;
    private String moderationReason;
    private String moderationRequestDate;
    private String moderationResponseDate;
    public int replicasCount;
    public int sourceId;
    public String sourceName;
    public String deactivationDate;
    public String deactivationReason;
    public String internalProcess;
    public String blackFriday;
    public String userName;
    public String userAssignmentDate;
    public String account;
    public String rafoneExpirationDate;
    public String rafoneStatusId;
    public String rafoneStatusName;
    public String commentary;
    public String insertionDate;
    public String closedDate;
    public String complaintResponseContent;
    public String complaintResponseDate;
    public String ratingTime;
    public String rating;
    public String ratingDate;
    public String contactUs;
    public String ruleId;
    public String active;
}
