package com.hyundaimotors.hmb.cdppapp.dto;

import java.util.List;

import com.hyundaimotors.hmb.cdppapp.payload.IFHMBINNOCEANCDPP0034.Accessory;
import com.hyundaimotors.hmb.cdppapp.payload.IFHMBINNOCEANCDPP0034.Part;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class IFHMBINNOCEANCDPP0034Dto {
    private int rowId;
    private String protocalResult;

    private String protocol;
    private String reason;
    private String level1;
    private String level2;
    private String level3;
    private String level4;
    private String source;
    private String method;
    private String description;
    private String status;
    private String priority;
    private String solution;
    private String serialNumber;
    private String anonymousFlag;
    private String contactId;
    private String accountId;
    private String tendency;
    private String satisfaction;
    private String dealerId;
    private String causingArea;
    private String imobilizationDate;
    private String relatedModel;
    private String quoteDescription;
    private String engineTransmission;
    private String version;
    private String versionPrice;
    private String color;
    private String colorPrice;
    private String finalPrice;
    private String carReplacementIntention;
    private String roadserviceRequest;
    private String integrationId;
    private String tdConfirmed;
    private String tdTime;
    private String tdDate;
    private String salesrepId;
    private String pneFlag;
    private String campaignId;
    private String sourceTag;
    private String estoque;
    private String medium;
    private String content;
    private String campaign;
    private String additionalComments;
    private String causingPerson;
    private String custRepresentative;
    private String custRepresentativeRel;
    private String diagnosisDifficultyFlg;
    private String diagnosisPendingFlg;
    private String dlrDescription;
    private String dlrFup;
    private String dlrPending;
    private String dlrRetractionFlg;
    private String dlrReversal;
    private String hotlineFlg;
    private String hotlineNum;
    private String hotlineOpenDt;
    private String purchaseProposalNum;
    private String pwaFlg;
    private String pwaNum;
    private String pwaOpenDt;
    private String recurrenceFlg;
    private int recurrenceNum;
    private String vehicleDeliveryDt;
    private String vehicleDeliveryFlg;
    private String wantsLoan;
    private String loanType;
    private int installmentsAmt;
    private int downPayment;
    private String usedCarAsDownPaymnt; 
    private String dlrTemperature;
    private String paymntDate;
    private String paymntMethod;
    private String paymntStatus;
    private String reservationAmount;
    private String form;
    private String schedDt;
    private String schedType;
    private String usedBrand;
    private String usedChassi;
    private String usedColor;
    private String usedKm;
    private String usedMaxPrice;
    private String usedMedPrice;
    private String usedMinPrice;
    private String usedModel;
    private String usedPlate;
    private String usedVersion;
    private String usedYear;

    List<Accessory> listOfAccessories;
    List<Part> listOfParts;
    private String errorSpcCode;
    private String errorSpcMessage;
}
