package com.hyundaimotors.hmb.cdppapp.dto;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Getter
@Setter
public class s_contact_xDto {    
    private String row_id;
    private String created;
    private String created_by;
    private String last_upd;
    private String last_upd_by;
    private String dcking_num;
    private String modification_num;
    private String conflict_id;
    private String par_row_id;
    private String attrib_08;
    private String attrib_09;
    private String attrib_10;
    private String attrib_11;
    private String attrib_12;
    private String attrib_13;
    private String attrib_14;
    private String attrib_15;
    private String attrib_16;
    private String attrib_17;
    private String attrib_18;
    private String attrib_19;
    private String attrib_20;
    private String attrib_21;
    private String attrib_22;
    private String attrib_23;
    private String attrib_24;
    private String attrib_25;
    private String attrib_26;
    private String attrib_27;
    private String attrib_28;
    private String attrib_29;
    private String attrib_30;
    private String attrib_31;
    private String attrib_32;
    private String attrib_33;
    private String attrib_56;
    private String attrib_57;
    private String attrib_58;
    private String attrib_59;
    private String attrib_60;
    private String attrib_61;
    private String attrib_62;
    private String attrib_63;
    private String attrib_64;
    private String db_last_upd;
    private String attrib_01;
    private String attrib_02;
    private String attrib_03;
    private String attrib_04;
    private String attrib_05;
    private String attrib_06;
    private String attrib_07;
    private String attrib_34;
    private String attrib_35;
    private String attrib_36;
    private String attrib_37;
    private String attrib_38;
    private String attrib_39;
    private String attrib_40;
    private String attrib_41;
    private String attrib_42;
    private String attrib_43;
    private String attrib_44;
    private String attrib_45;
    private String attrib_46;
    private String attrib_47;
    private String attrib_48;
    private String attrib_49;
    private String attrib_50;
    private String attrib_51;
    private String attrib_52;
    private String attrib_53;
    private String attrib_54;
    private String attrib_55;
    private String db_last_upd_src;
    private String cod_coordenada;
    private String coord_x;
    private String coord_y;
    private String factor_05_1;
    private String factor_05_2;
    private String factor_05_3;
    private String factor_05_4;
    private String factor_05_5;
    private String factor_05_6;
    private String grupo_mosaic_05;
    private String lived_city1;
    private String lived_country;
    private String lived_post_code1;
    private String lived_region;
    private String lived_str_suppl1;
    private String lived_str_suppl2;
    private String lived_str_suppl3;
    private String sscc_01;
    private String temp_city1;
    private String temp_country;
    private String temp_post_code1;
    private String temp_region;
    private String temp_str_suppl1;
    private String temp_str_suppl2;
    private String temp_str_suppl3;
    private String tipo_tramo_05;
    private String tramo_mosaic_05;
    private String x_called_by;
    private String x_employee_flg;
    private String x_literacy;
    private String x_receive_call;
    private String x_receive_email;
    private String x_receive_letter;
    private String x_receive_sms;
    private String x_replaced_row_id;
    private String x_seg_behavioral;
    private String x_seg_facebook;
    private String x_seg_google;
    private String x_seg_interest;
    private String x_seg_life_cycle;
    private String x_seg_value;
    private String x_snt_birth_date_flg;
    private String x_snt_cell_ph_num_flg;
    private String x_snt_cpf_flg;
    private String x_snt_email_addr_flg;
    private String x_snt_fst_name_flg;
    private String x_snt_home_ph_num_flg;
    private String x_snt_last_name_flg;
    private String x_snt_work_ph_num_flg;
    private String x_amount_children;
    private String x_amount_friends;
    private String x_cnh_exp_date;
    private String x_loyalty_act_dt;
    private String x_loyalty_crm_index;
    private String x_loyalty_engagement;
    private String x_loyalty_exp_dt;
    private String x_loyalty_optin_flg;
    private String x_loyalty_satisfaction;
    private String x_loyalty_status;
    private String x_already_customer;
    private String x_favorite_dealer;
}
